name: ambsowiml
dependencies:
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - pandas=1.0.3
  - scikit-learn=0.20.3
  - scipy=1.4.1
  - seaborn=0.10.0
  - _py-xgboost-mutex=2.0
  - libxgboost=0.90
  - py-xgboost=0.90
  - pip:
    - heliosat==0.4.0
    - predstorm==0.1.1

